### ISSUE TITLE
Unstable local position estimates when using PX4FLOW

### ISSUE THREAD

**Issue by rr2-ip** [PX4/Flow#102]
Hi there!

I've been trying to implement a PX4FLOW camera + LeddarOne rangefinder on my Intel Aero RTF Drone for some time now. I have the PX4FLOW camera connected via I2C to the Telemetry port. The LeddarOne is connected to the TX and RX pins of the Telemetry port.
I have updated the PX4FLOW firmware, enabled the driver and started it on boot. When off the ground, the OPTICAL_FLOW_RAD.quality is consistently over 200. In this time I receive meaningful local position estimates from the PX4FLOW.

The problem is that, while the drone is stationary (either being carried in the air, or on the ground) with PX4FLOW active, the estimates will frequently become unstable and continue to oscillate. While I am moving the drone around (carry testing) the estimates move as they should. Even if the estimates are unstable, then I move the drone in the air (specifically roll), the estimates correct themselves temporarily. When the drone is stationary again, it will return to its unstable state after a very short amount of time. After rebooting the drone, the time is seemingly random until the estimates become stable once again.

Can someone please help me diagnose the source of this instability?

I've attached a log from a period of time where the drone was simply stationary on the desk, then the estimates became unstable. I've had a look through but I can't seem to find the trigger for the instability.
unstable_local_position.zip

Kind Regards

**Comment by rr2-ip** [comment]
I've narrowed down the cause as to what triggers the instability in the EKF. When the drone is sitting on the desk, both the OPTICAL_FLOW_RAD.quality and OPTICAL_FLOW_RAD.distance = zero in MAVLINK. After about 5-10 minutes of constant zero quality and distance, there is a single spike up to about 250 quality, and at the same time a single spike in distance = 66. The local position estimates then become unstable as seen in the attached picture.

It is also worth noting that the spike in the distance reading is the same magnitude of 66, and occurs every time the position estimates become unstable.

**Comment by rr2-ip** [comment]
@ChristophTobler Have you encountered this before? I feel like I'm close to a fix and your expertise might get me over the line.

**Comment by dominiknatter** [comment]
Hi @rr2-ip,

I think I have similar issues (see [here](https://github.com/PX4/Firmware/issues/14165)), i.e. spiking optical flow values making the EKF2 go crazy. Did you ever manage to solve it? I currently think it could be a connection issue because we both use I2C on the TELEMETRY port instead of (potentially more reliable) UART.

Thanks,
Dominik
