### ISSUE TITLE
Links in the readme become unavailable

### ISSUE THREAD

**Issue by Jeoker** [PX4/Flow#117]
Hi, the links in the readme seem to be obselete, can you please update them?

**Comment by mike239x** [comment]
The latest dev duige I could find is this - https://docs.px4.io/master/en/sensor/px4flow.html - and it is also somewhat obselete.

**Comment by mike239x** [comment]
Fixed via 6c8cdb3cc04a5854a7b50e76e267e35507a0a0c4
