### ISSUE TITLE
nan x,y velocities

### ISSUE THREAD

**Issue by scott-eddy** [PX4/Flow#24]
Hello all,
Recently I flashed by Flow with the latest stable release of the firmware through QGroundControl.  This has enabled us to view the camera image from the ros node that is being developed here: http://wiki.ros.org/px4flow_node.

However, after the firmware flash the flow_comp_m_x and flow_comp_m_y values often return a value of nan.  Looking through the firmware here I think the only way this could happen is at line 395 of main.c when flow_copmx/y are divided by get_time_between_images() if get_time_between_images() returned 0.

I'm curious if anyone else is getting nan values for velocities and if indeed the problem is in get_time_between_images().  

Any advice of where to investigate would be much appreciated.

**Comment by cpamritkar** [comment]
Hello all,
I am also facing same issue when connected to PC via USB and try to read the MAVLink packets. The sensor is communicating fine when accessed through MissionPlanner.

Any advice for the same is appreciated.
