### ISSUE TITLE
Garbage image in low...middle light conditions

### ISSUE THREAD

**Issue by DrTon** [PX4/Flow#41]
Image from PX4FLOW looks ok when I point it to outside from my window but completely garbarge when I point somewhere in room (not too dark). On attached image something in the middle: brightest part of image are ok, but the rest is garbage. Observation of flow_x/flow_y/quality shows that it's NOT transmission problem, but problem of reading from sensor.
Hardware: PX4FLOW v1.3
Firmware: latest master for today (baf60dc)

![qgc_flow1](https://cloud.githubusercontent.com/assets/4341525/5916299/03729896-a610-11e4-82f4-9793b526bcad.png)

**Comment by LorenzMeier** [comment]
See #44, closing.
