### ISSUE TITLE
I2C Integral Frame does not respond properly

### ISSUE THREAD

**Issue by ecmnet** [PX4/Flow#43]
I am trying to read the second I2C frame (integral frame) each 50ms. So far I only managed to get the frame ONCE. After that, data is not updated any more. The first frame however works properly.

**Comment by ecmnet** [comment]
Solved: I have to read 26 bytes instead of 25. Why I don't know.

**Comment by thomasck** [comment]
BRUH you saved me on this. I have been trying to read this damn integral frame for weeks.
 CHEERS!
