### ISSUE TITLE
angular velocity compensation using Z gyro

### ISSUE THREAD

**Issue by thedinuka** [PX4/Flow#50]
According to the ICRA 2013 paper, angular compensation should also use the yaw rate to account for the flow induced due to yaw. But looking at flow.c, I see that z_rate (rate of z axis (or yaw) gyro) is not being used for gyro compensation. There is probably a good reason for doing so. Appreciate if someone can give me point me in the right direction to understand why it was done so.

**Comment by LorenzMeier** [comment]
We're doing this on the autopilot.
