### ISSUE TITLE
px4Flow i2c  frame  to FMU   confused me

### ISSUE THREAD

**Issue by yl5006** [PX4/Flow#55]
first :px4Flow calculates optical flow  at 400Hz ,but FMU px4Flow driver  default conversion at 10Hz,
      is it suit able for postion estimator ?so I tried average data ,and set FMU converdion quickly,but it works not well .or because optical flow datas are not accuracy. 
    secend：px4Flow up accumulated_flow_x and  accumulated_flow_y to I2c frame ，It is accumulated rad/s,not angular speed .it is some mistake here?

**Comment by LorenzMeier** [comment]
There are no mistakes, the documentation is accurate. Please use the mailing list to ask questions. https://groups.google.com/forum/#!forum/px4users
