### ISSUE TITLE
setup firmware "Beginner"

### ISSUE THREAD

**Issue by Mahmoud-Teama** [PX4/Flow#74]
how do i upload this firmware to the PX4 ?
also i updated the firmware through QGround software and the Ground distance is always zero even the built in Sonar works fine alone
thanks for your help

**Comment by mhkabir** [comment]
```make``` and then  ```make upload-usb```

**Comment by julianoes** [comment]
What kind of sonar do you want to use? And how is it connected?

**Comment by ChristophTobler** [comment]
@Mahmoud-Teama Have a look at the [dev guide](https://dev.px4.io/en/tutorials/optical_flow.html)
