### ISSUE TITLE
Cannot read values from PX4Flow

### ISSUE THREAD

**Issue by kanishkanamdeo** [PX4/Flow#89]
So I have bought this PX4Flow clone from Aliexpress and it's not working. The only output I get is the video feed that I can view on the QGC. All other values are not returned. Help?

Also, this is the link to the sensor I've purchased 

https://www.aliexpress.com/item/JMT-PX4FLOW-V1-3-1-Optical-Flow-Sensor-Smart-Camera-with-MB1043-Ultrasonic-Module-Sonar-for/32766580894.html?ws_ab_test=searchweb0_0,searchweb201602_2_10152_10065_10151_10068_10084_10083_10080_10082_10081_10110_10136_10137_10175_10111_10060_10138_10112_10113_10062_10156_10114_10056_10055_10054_10059_10099_10078_10079_10103_10073_10102_10096_10070_10148_10123_10147_10052_10053_10124_10142_10107_10050_10143_10051,searchweb201603_9,afswitch_1,ppcSwitch_5&btsid=304cea8f-a92e-4dac-ad9c-ba268336508f&algo_expid=f2f9d27d-e708-48dc-a2e6-64f803c7f966-1&algo_pvid=f2f9d27d-e708-48dc-a2e6-64f803c7f966

**Comment by trigger1996** [comment]
Lots of guys said that optflow didn't work well.
Look up these in ardupilot or pixhawk official site, and, don't forget to make some changes in flow
and I've tried, seems ardupilot 3.5.0-dev doesn't support optflow, perhaps the earlier version works.

https://dev.px4.io/en/tutorials/optical_flow.html
and sorry I haven't found any ardupilot documents in English

**Comment by ChristophTobler** [comment]
I'm sorry, but I guess we can't help you with hardware clones as we don't use/have them.
