### ISSUE TITLE
Unable to make

### ISSUE THREAD

**Issue by sluthra1** [PX4/Flow#99]
Hello I am trying to make the flow library on my MacBook, I've installed the toolchain. I am able to compile PX4, but when I run make on the px4flow firmware libraries I cannot complete the make. The first problems were with python incompatibilities (mode 'rob' and cString vs io.bytesIO), but now with those resolved I get the error":

Flow/Tools/make_can_boot_descriptor.py", line 283, in <module>
    out_image.write(bootloader_image)
TypeError: a bytes-like object is required, not 'str'

**Comment by jlecoeur** [comment]
This is a problem of compatibility between python 2 and python 3. I fixed it in PR #96 .

The relevant changes are in https://github.com/PX4/Flow/pull/96/commits/dd2425bd02fd8bb02aded8d36e0eb60fdad7b866

**Comment by EdXian** [comment]
Hi @jlecoeur ,
I got the following problem:

![screenshot from 2018-06-18 15-31-40](https://user-images.githubusercontent.com/28064159/41523531-eb14b70c-730c-11e8-8ac0-f5b6bc243802.png)


How do I fix it?

**Comment by jlecoeur** [comment]
@EdXian this is a different problem, please open separate issues in this case.

Your problem is that your compiler version is not allowed, you can either:
- install one of the versions suggested in the error message
- add 7.2.1 near line 57 of file `src/Flow/makefile/baremetal/toolchain_gnu-arm-eabi.mk`

**Comment by mike239x** [comment]
Python vs Python2 issue was fixed in 8fa8fdcd7be6ea3ac370379db87003927932a3e7.
The default compiler version on Ubuntu 18.04 is 6.3.1, so 7.2.1 is a bit too new, maybe will get tested and added later.
